services:
  backend:
    build: ./backend
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    restart: unless-stopped
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped



