package com.lfav07.agentscaffold.model.agent;


public enum CoreAgentType {
    BACKEND_ARCHITECT,
    BACKEND_ARCHITECT_REVIEWER,
    BACKEND_IMPLEMENTER,
    BACKEND_TESTER,
    FRONTEND_ARCHITECT,
    FRONTEND_ARCHITECT_REVIEWER,
    FRONTEND_IMPLEMENTER,
    FRONTEND_TESTER,
    FINAL_REVIEWER
}
